### ISSUE TITLE
Inline LaTeX display offset 

### ISSUE THREAD

**Issue by Moelf** [LuxDL/DocumenterVitepress.jl#167] opened 2024-07-12 05:32 UTC
https://juliahep.github.io/JetReconstruction.jl/previews/PR66/

Looks like 
![Screenshot_20240712_073215_Firefox Nightly](https://github.com/user-attachments/assets/d06c12e2-e4b1-412b-b607-b8a641580ab5)

**Comment by avik-pal** [comment] 2024-07-12 05:35
Duplicate of https://github.com/LuxDL/DocumenterVitepress.jl/issues/161

**Closed** 2024-07-12 05:44 UTC

**Comment by asinghvi17** [comment] 2024-07-12 06:10
Do you have custom CSS?

**Comment by Moelf** [comment] 2024-07-12 08:30
I don't think so. copied from templates in this repo

**Comment by asinghvi17** [comment] 2024-07-12 10:03
OK, looks like we might be able to fix this in the repo then.  Someone over in #161 mentioned a potential fix.

**Comment by Moelf** [comment] 2024-07-12 10:21
can report that does fix it
